title: HYDROBOT

email:
  - mira10@seas.upenn.edu
  - lubha@seas.upenn.edu
  - corobin@seas.upenn.edu

description: Modern robotics, engineering and STEM projects.

# GitHub Pages settings
url: "https://mira10-git.github.io"
baseurl: "/robotgirlz.github.io"

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

